googleAnalytics = "G-SDD1PJ939R"
baseURL = 'https://huangjing.me/'
languageCode = 'zh-Hans'
title = 'Huang Jing'
theme = 'hugo-book'
hasCJKLanguage = true



[[markup]]
  [[markup.goldmark]]
    [[markup.goldmark.parser]]
      [[markup.goldmark.parser.attribute]]
        block = true
    [[markup.goldmark.renderer]]
      unsafe = true
  [[markup.tableOfContents]]
    startLevel = 1


[[menu.before]]
  name = "Blog"
  pageRef = '/posts'
  weight = 1
    
[[menu.after]]
  name = "Monoify"
  url = "https://monoify.io"
  weight = 1

[[menu.after]]
  name = "Github"
  url = "https://github.com/eatgrass"
  weight = 2


# [params]
#   BookTheme = "dark"
