baseURL = 'https://huangjing.me/'
languageCode = 'zh-Hans'
title = 'Huang Jing'
theme = 'hugo-book'


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1

# [params]
#   BookTheme = "dark"
