googleAnalytics = "G-SDD1PJ939R"
baseURL = 'https://huangjing.me/'
languageCode = 'zh-Hans'
title = 'Huang Jing'
theme = 'hugo-book'
hasCJKLanguage = true



[[markup]]
  [[markup.goldmark]]
    [[markup.goldmark.parser]]
      [[markup.goldmark.parser.attribute]]
        block = true
    [[markup.goldmark.renderer]]
      unsafe = true
  [[markup.tableOfContents]]
    startLevel = 1

[menu]
[[menu.before]]
  name = '读书'
  pageRef = '/categories/读书/'
  weight = 1

[[menu.before]]
  name = "随笔"
  pageRef = '/categories/随笔/'
  weight = 2

# [params]
#   BookTheme = "dark"
